# -*- coding: utf-8 -*-
import pandas as pd
import utilChartsTest as uct


# Generate example plots for a library
# Select a library, run the func to generate the png files and csv
# Then run the html generator for that lib
def plotMultiLibraryExamplesInit():
    lib_utilChartsTest = 'utilChartsTest'
    funcList_utilChartsTest = [
            [uct.plotBarGroupedTest],
            [uct.plotBarStackedGroupedTest],
            [uct.plotBarStackedTest],
            [uct.plotBarTest],
            [uct.plotBoxTest],
            [uct.plotHistogramTest],
            [uct.plotLineMultiTest],
            [uct.plotLineTest],
            [uct.plotScatterMultiTest],
            [uct.plotScatterTest]]
    plotMultiLibraryExamples(aLibName=lib_utilChartsTest, 
                             aFuncList=funcList_utilChartsTest)


# Plot example outputs for given library and function list
# Generates a csv file with a output lookup info
def plotMultiLibraryExamples(aLibName='', aFuncList=[]):
    f = open('ReportsAutoGenerated/' + aLibName + '.csv', 'w')
    f.write('Library,FuncName,ExampleOutput\n')
    for fn in aFuncList:
        print(fn[0].__name__)
        pngName = fn[0]()
        funcName = str(fn[0].__name__)
        f.write(aLibName + ',' + funcName + ',' + pngName + '\n' )
    f.close()
    csvFile = aLibName
    genHtmlFromCsv(aCsvFile=csvFile)
    

# Create html file from csv for function example outputs
def genHtmlFromCsv(aCsvFile='utilChartsTest'):
    examplesDF = pd.read_csv('ReportsAutoGenerated/' + aCsvFile + '.csv')
    f = open('ReportsAutoGenerated/' + aCsvFile + '.html', 'w')
    f.write('<!DOCTYPE html>\n')
    f.write('<html>\n')
    f.write('<head>\n')
    f.write('<title>' +  aCsvFile + '</title>\n')
    f.write('</head>\n')
    f.write('<body>\n')
    f.write('<h1>Example output for funcs in library ' + aCsvFile + '</h1>\n')
    #f.write('<p>This is a paragraph.</p>\n')
    for index, row in examplesDF.iterrows():
        f.write('<h2>' + row['FuncName'] + '</h2>\n')
        f.write('<img src="' + row['ExampleOutput'] + '" alt="Sample">\n')
    f.write('</body>\n')
    f.write('</html>\n')
    f.close()